import App from '../src/core/app.class';

export default function (app: App) {
  return {
    keys: {
      backtop: { value: 'g g', priority: 270 },
      backbottom: { value: 'G', priority: 271 },
      feedback: { value: 'e d', checked: true, priority: 480 },
      focus: { value: 'a s', checked: true, priority: 140 },
      fullscreen: { value: 'f u', checked: true, priority: 60 },
      fullscreen_exit: { priority: 61, value: 'f e', checked: true },
      whitelist: { value: 'w l', checked: true, priority: 120 },
      whitelist_site: { value: 'w s', priority: 121 },
      blacklist: { value: 'b l', checked: true, priority: 122 },
      blacklist_site: { value: 'b s', priority: 123 },
      manual: { value: 'h l', checked: true, priority: 130 },
      paper: { value: 'p r', checked: true, priority: 80 },
      enter_or_exit: { value: 'a a', checked: true, priority: 6 },
      print: { value: 'p p', checked: true, priority: 40 },
      exit: { value: 'esc', checked: true, priority: 10 },
      exitclose: { value: 'x x', checked: true, priority: 20 },
      imagehide: { value: 'h p', checked: true, priority: 30 },
      setting: { value: 's t', checked: true, priority: 50 },
      setting__style: { value: 's l', priority: 601 },
      setting__skin: { value: 't m', priority: 602 },
      setting__layout: { value: 'l y', priority: 603 },
      setting__toolbar: { value: 't b', priority: 605 },
      setting__keys: { value: ',', priority: 606 },
      setting__menu: { value: 'c m', priority: 607 },
      setting__lists: { value: 'm w', priority: 608 },
      setting__plugin: { value: 'a p', priority: 609 },
      setting__config: { value: 'c f', priority: 611 },
      setting__about: { value: 'a b', priority: 612 },
    },
    menu: {
      backtop: { title: app.i10n('backtop'), priority: 270 },
      backbottom: { title: app.i10n('backbottom'), priority: 271 },
      feedback: { title: app.i10n('feedback'), checked: true, priority: 480 },
      focus: { title: app.i10n('focus'), checked: true, priority: 140 },
      fullscreen: { title: app.i10n('fullscreen'), priority: 60 },
      fullscreen_exit: { title: app.i10n('fullscreen_exit'), priority: 61 },
      whitelist: {
        title: app.i10n('add_whitelist'),
        checked: true,
        priority: 120,
      },
      whitelist_site: { title: app.i10n('add_whitelist_site'), priority: 121 },
      blacklist: {
        title: app.i10n('add_blacklist'),
        checked: true,
        priority: 122,
      },
      blacklist_site: { title: app.i10n('add_blacklist_site'), priority: 123 },
      manual: { title: app.i10n('manual'), checked: true, priority: 130 },
      paper: { title: app.i10n('paper'), priority: 80 },
      enter_or_exit: {
        title: app.i10n('enter_or_exit'),
        checked: true,
        priority: 6,
      },
      print: { title: app.i10n('print'), priority: 40 },
      exit: { title: app.i10n('exit'), priority: 10 },
      exitclose: { title: app.i10n('exitclose'), priority: 20 },
      imagehide: { title: app.i10n('imagehide'), priority: 30 },
      setting: { title: app.i10n('setting'), checked: true, priority: 50 },
      setting__style: { title: app.i10n('style'), priority: 601 },
      setting__skin: { title: app.i10n('skin'), priority: 602 },
      setting__layout: { title: app.i10n('layout'), priority: 603 },
      setting__toolbar: { title: app.i10n('toolbar'), priority: 605 },
      setting__keys: { title: app.i10n('keys'), priority: 606 },
      setting__menu: { title: app.i10n('menu'), priority: 607 },
      setting__lists: { title: app.i10n('lists'), priority: 608 },
      setting__plugin: { title: app.i10n('plugin'), priority: 609 },
      setting__config: { title: app.i10n('config'), priority: 611 },
      setting__about: { title: app.i10n('about'), priority: 612 },
    },
    toolbar: {
      backtop: {
        group: 2,
        icon: 'UpOutlined',
        title: app.i10n('backtop'),
        priority: 270,
      },
      backbottom: {
        group: 2,
        priority: 271,
        icon: 'DownOutlined',
        title: app.i10n('backbottom'),
      },
      feedback: {
        group: 4,
        checked: true,
        icon: 'FeedbackOutline',
        title: app.i10n('feedback'),
        priority: 480,
      },
      fullscreen: {
        group: 0,
        checked: true,
        icon: 'FullscreenOutlined',
        title: app.i10n('fullscreen'),
        priority: 60,
      },
      fullscreen_exit: {
        group: 0,
        priority: 61,
        checked: true,
        icon: 'FullscreenExitOutlined',
        title: app.i10n('fullscreen_exit'),
      },
      whitelist: {
        group: 1,
        checked: true,
        icon: 'WhitelistOutline',
        title: app.i10n('toggle_whitelist'),
        priority: 120,
      },
      whitelist_site: {
        group: 1,
        priority: 121,
        icon: 'WhitelistSiteOutline',
        title: app.i10n('toggle_whitelist_site'),
      },
      blacklist: {
        group: 1,
        priority: 122,
        checked: true,
        icon: 'BlacklistOutline',
        title: app.i10n('toggle_blacklist'),
      },
      blacklist_site: {
        group: 1,
        priority: 122,
        icon: 'BlacklistSiteOutline',
        title: app.i10n('toggle_blacklist_site'),
      },
      manual: {
        group: 1,
        icon: 'SelectOutlined',
        title: app.i10n('manual'),
        priority: 130,
      },
      paper: {
        group: 0,
        checked: true,
        icon: 'PaperOutline',
        title: app.i10n('paper'),
        priority: 80,
      },
      print: {
        group: 0,
        checked: true,
        icon: 'PrinterOutlined',
        title: app.i10n('print'),
        priority: 40,
      },
      exit: {
        group: 0,
        priority: 10,
        checked: true,
        icon: 'CloseOutlined',
        title: app.i10n('exit'),
      },
      exitclose: {
        group: 0,
        priority: 20,
        icon: 'PoweroffOutlined',
        title: app.i10n('exitclose'),
      },
      imagehide: {
        group: 0,
        priority: 30,
        icon: 'ImageHideOutline',
        title: app.i10n('imagehide'),
      },
      setting: {
        group: 0,
        checked: true,
        icon: 'SettingOutlined',
        title: app.i10n('setting'),
        priority: 50,
      },
      setting__style: {
        group: 4,
        priority: 601,
        icon: 'FormatPainterOutlined',
        title: app.i10n('style'),
      },
      setting__skin: {
        group: 4,
        priority: 602,
        icon: 'SkinOutlined',
        title: app.i10n('skin'),
      },
      setting__layout: {
        group: 4,
        priority: 603,
        icon: 'LayoutOutlined',
        title: app.i10n('layout'),
      },
      setting__toolbar: {
        group: 4,
        priority: 605,
        icon: 'ToolOutlined',
        title: app.i10n('toolbar'),
      },
      setting__keys: {
        group: 4,
        priority: 606,
        icon: 'ThunderboltOutlined',
        title: app.i10n('keys'),
      },
      setting__menu: {
        group: 4,
        priority: 607,
        icon: 'MenuOutlined',
        title: app.i10n('menu'),
      },
      setting__lists: {
        group: 4,
        priority: 608,
        icon: 'ProfileOutlined',
        title: app.i10n('lists'),
      },
      setting__plugin: {
        group: 4,
        priority: 609,
        checked: true,
        icon: 'AppstoreOutlined',
        title: app.i10n('plugin'),
      },
      setting__config: {
        group: 4,
        priority: 611,
        icon: 'DatabaseOutlined',
        title: app.i10n('config'),
      },
      setting__about: {
        group: 4,
        priority: 612,
        icon: 'ExclamationCircleOutlined',
        title: app.i10n('about'),
      },
    },
    setting: {
      plugin: [
        'lists',
        'toolbar',
        'keys',
        'menu',
        'backtop',
        'fullscreen',
        'manual',
        'outline',
        'print',
        'paper',
        'feedback',
        'focus',
      ],
    },
  };
}
