export default {
  en: {
    autorun: 'auto start',
    autorun_tooltip:
      'The algorithm needs to be improved, please open it with caution',
    backtop: 'Back to top',
    backbottom: 'Navigate to the bottom',
    feedback: 'feedback',
    focus: 'Highlight the original',
    focus_desc:
      'Without entering reading mode, highlight the text in the original text',
    focus_opacity: 'Non-text transparency in original text',
    fullscreen: 'View in full screen',
    fullscreen_exit: 'Exit Full Screen',
    autofullscreen: 'automatic full screen',
    autofullscreen_tooltip: 'Enter the Circle full screen display',
    keys: 'hot key',
    keys_desc: 'Use shortcut keys to improve operational efficiency',
    keys_msg:
      'Press the key after selecting the input box, support single key, combination key and double-click single key',
    only_in_reader: 'Only supports running in reading mode',
    lists: 'Black and white list',
    whitelist: 'whitelist',
    blacklist: 'blacklist',
    add_whitelist: 'Add the current page to the whitelist',
    remove_whitelist: 'Remove current page from whitelist',
    toggle_whitelist: 'Add or remove the current page to the whitelist',
    add_whitelist_site: 'Whitelist the current website',
    remove_whitelist_site: 'Remove current site from whitelist',
    toggle_whitelist_site: 'Add or remove the current site from the whitelist',
    add_blacklist: 'Add current page to blacklist',
    remove_blacklist: 'Remove current page from blacklist',
    toggle_blacklist: 'Add or remove the current page to the blacklist',
    add_blacklist_site: 'Add current site to blacklist',
    remove_blacklist_site: 'Remove current site from blacklist',
    toggle_blacklist_site: 'Add or remove current website from blacklist',
    lists_remove_success: 'Removed successfully',
    lists_add_success: 'Added successfully',
    title: 'title',
    url: 'URL',
    operate: 'operate',
    manual: 'Manual selection',
    manual_desc:
      'When the text recognition is wrong, assist in the recognition of the text. With the "rules", you can remember the choice',
    manual_alert:
      'Click the pop-up window at the bottom of the page to identify the wrong element (dotted border), slide the mouse to select the correct content and click OK',
    cover_picture: 'cover picture',
    time: 'time',
    body: 'content',
    select_done: 'complete selection',
    menu: 'right-click menu',
    notice: 'message box',
    outline: 'Article directory',
    outline_desc:
      'Automatically identify categories of content to quickly navigate to your point of interest',
    pin_outline: 'pinned directory',
    hidden_outline: 'hidden directory',
    paper: 'stationery effect',
    paper_desc: 'Letter-like reading experience',
    paper_tooltip: 'Similar to stationery background border',
    parser: 'parsing engine',
    parser_error:
      'Content identification failed, please use the "manual selection" plugin to assist in identifying the content',
    print: 'Print',
    print_desc: "Invoke the browser's print service",
    render: 'rendering engine',
    style: 'style',
    page: 'page',
    font: 'default font',
    cn_font: 'Chinese font',
    font_tooltip: 'The font needs to be installed on the system',
    default: 'system default',
    size: 'font size',
    width: 'page width',
    space: 'font spacing',
    lineheight: 'font line height',
    weight: 'font weight',
    blockspace: 'paragraph spacing',
    indent: 'First line indent',
    titlealign: 'title alignment',
    align: 'content alignment',
    imagealign: 'image alignment',
    imagehide: 'hide image',
    skin: 'theme',
    website: 'Official homepage',
    donate: 'Donate support',
    download: 'download',
    title1: 'first-level title',
    title2: 'secondary title',
    title3: 'tertiary heading',
    title4: 'Level 4 heading',
    title5: 'Level 5 heading',
    title6: 'Level 6 heading',
    layout: 'layout',
    margin: 'page margins',
    padding_tooltip: 'It takes effect only after the paper effect is enabled',
    copyright:
      'Browser extension Circle reading assistant layout, copyright owned by $URL$',
    exception: 'abnormal',
    vote_alert:
      'If the corresponding platform is not found, you can manually enter the expansion market, and give a good comment after searching for Circle ~',
    sure_to_close: "Don't show anymore after closing, are you sure?",
    enable: 'enable',
    disable: 'disabled',
    setting: 'Preferences',
    align_left: 'Align left',
    align_center: 'center align',
    align_right: 'Align right',
    align_justify: 'justified',
    reset: 'reset',
    reset_tooltip: 'revert to default',
    reset_all: 'Initialize all configurations',
    night: 'follow the system',
    style_night_tooltip: 'Follow the system to automatically switch styles',
    skin_night_tooltip: 'Follow the system to automatically switch themes',
    exitclose: 'log out and close the page',
    enter_or_exit: 'Enter/Exit Circle',
    exit: 'quit',
    plugin: 'application market',
    custom: 'customize',
    ok: 'OK',
    filter_nothing: 'No data found, try changing keywords',
    cancel: 'Cancel',
    remove: 'remove',
    edit: 'edit',
    delete: 'delete',
    add: 'Add to',
    learn_more: 'Learn more',
    required: 'Can not be empty',
    empty: 'No data',
    reset_confirm:
      'Are you sure to reset? All data such as black and white list, read later, etc. will be cleared',
    notice_placement_demo: 'Example of where the message appears',
    config: 'configure',
    local: 'local',
    sync_export: 'export',
    select_all: 'select all',
    sync_import: 'Import local configuration',
    about: 'about',
    follow: 'Follow us',
    follow_msg: 'Follow us for timely updates',
    wechat: 'the public',
    qq: 'QQ group',
    support: 'encouragement and support',
    support_msg:
      'Your encouragement and support are the greatest motivation for me',
    donate_coffee: 'buy me coffee',
    share_to_other: 'share with friends',
    vote: 'Five-star praise',
    vote_msg: 'If it helps you, give us a five-star review 🤪',
    to_vote: 'Five-star praise',
    to_feedback: 'feedback and suggestions',
    link: 'Most used link',
    usage: "user's guidance",
    agreement: 'User Agreement',
    privacy: 'Privacy Policy',
    faq: 'common problem',
    update: 'new version update',
    download_latest: 'download new version',
    version: 'current version',
    search_in_setting: 'search in preferences',
    toolbar: 'toolbar',
    toolbar_msg: 'Click the icon to customize the color',
    itemspace: 'Toolbar item spacing',
    groupspace: 'Toolbar group spacing',
  },
  ja: {
    autorun: '自動スタート',
    autorun_tooltip:
      'アルゴリズムを改善する必要があります。注意して開いてください',
    backtop: 'トップに戻る',
    backbottom: '一番下に移動',
    feedback: 'フィードバック',
    focus: 'オリジナルを際立たせる',
    focus_desc:
      '読み取りモードに入らずに、元のテキストのテキストを強調表示します',
    focus_opacity: '元のテキストの非テキスト透過性',
    fullscreen: '全画面表示',
    fullscreen_exit: '全画面表示を終了',
    autofullscreen: '自動フルスクリーン',
    autofullscreen_tooltip: 'サークル全画面表示に入る',
    keys: 'ホットキー',
    keys_desc: 'ショートカットキーを活用して業務効率アップ',
    keys_msg:
      '入力ボックスを選択した後にキーを押し、単一キー、組み合わせキー、および単一キーのダブルクリックをサポートします',
    only_in_reader: '読み取りモードでの実行のみをサポート',
    lists: '白黒リスト',
    whitelist: 'ホワイトリスト',
    blacklist: 'ブラックリスト',
    add_whitelist: '現在のページをホワイトリストに追加',
    remove_whitelist: '現在のページをホワイトリストから削除',
    toggle_whitelist: '現在のページをホワイトリストに追加または削除する',
    add_whitelist_site: '現在の Web サイトをホワイトリストに登録する',
    remove_whitelist_site: '現在のサイトをホワイトリストから削除',
    toggle_whitelist_site: '現在のサイトをホワイトリストに追加または削除します',
    add_blacklist: '現在のページをブラックリストに追加',
    remove_blacklist: '現在のページをブラックリストから削除',
    toggle_blacklist: '現在のページをブラックリストに追加または削除します',
    add_blacklist_site: '現在のサイトをブラックリストに追加',
    remove_blacklist_site: '現在のサイトをブラックリストから削除',
    toggle_blacklist_site:
      '現在の Web サイトをブラックリストに追加または削除する',
    lists_remove_success: '正常に削除されました',
    lists_add_success: '正常に追加されました',
    title: '題名',
    url: 'URL',
    operate: '操作する',
    manual: '手動選択',
    manual_desc:
      'テキスト認識が間違っている場合、テキストの認識を支援します。 「ルール」があると、選択を覚えることができます',
    manual_alert:
      'ページの下部にあるポップアップ ウィンドウをクリックして間違った要素 (点線の境界線) を特定し、マウスをスライドして正しいコンテンツを選択し、[OK] をクリックします。',
    cover_picture: '表紙絵',
    time: '時間',
    body: 'コンテンツ',
    select_done: '完全な選択',
    menu: '右クリック メニュー',
    notice: 'メッセージボックス',
    outline: '記事ディレクトリ',
    outline_desc:
      'コンテンツのカテゴリを自動的に識別して、関心のあるポイントにすばやく移動します',
    pin_outline: '固定されたディレクトリ',
    hidden_outline: '隠しディレクトリ',
    paper: '文具効果',
    paper_desc: '文字のような読書体験',
    paper_tooltip: '文房具の背景の境界線に似ている',
    parser: '解析エンジン',
    parser_error:
      'コンテンツの識別に失敗しました。コンテンツの識別に役立つ「手動選択」プラグインを使用してください',
    print: '印刷する',
    print_desc: 'ブラウザの印刷サービスを呼び出す',
    render: 'レンダリングエンジン',
    style: 'スタイル',
    page: 'ページ',
    font: 'デフォルトのフォント',
    cn_font: '中国語フォント',
    font_tooltip: 'フォントをシステムにインストールする必要があります',
    default: 'システムのデフォルト',
    size: 'フォントサイズ',
    width: 'ページ幅',
    space: 'フォント間隔',
    lineheight: 'フォント行の高さ',
    weight: 'フォントの太さ',
    blockspace: '段落間隔',
    indent: '最初の行のインデント',
    titlealign: 'タイトルの配置',
    align: 'コンテンツの配置',
    imagealign: '画像の配置',
    imagehide: '画像を隠す',
    skin: 'テーマ',
    website: '公式ホームページ',
    donate: '支援を寄付する',
    download: 'ダウンロード',
    title1: '最初のレベルのタイトル',
    title2: '副題',
    title3: '三次見出し',
    title4: 'レベル 4 の見出し',
    title5: 'レベル 5 の見出し',
    title6: 'レベル 6 の見出し',
    layout: 'レイアウト',
    margin: 'ページ余白',
    padding_tooltip: '紙の効果が有効になった後にのみ有効になります',
    copyright:
      'ブラウザ拡張機能 サークル リーディング アシスタント レイアウト、著作権は $URL$ が所有',
    exception: '異常な',
    vote_alert:
      '対応するプラットフォームが見つからない場合は、手動で拡張市場に参入し、サークルを検索してから良いコメントを与えることができます〜',
    sure_to_close: '閉店後はもう表示しないでよろしいですか？',
    enable: '有効',
    disable: '無効',
    setting: '環境設定',
    align_left: '左揃え',
    align_center: '中央揃え',
    align_right: '右揃え',
    align_justify: '正当化された',
    reset: 'リセット',
    reset_tooltip: 'デフォルトに戻す',
    reset_all: 'すべての構成を初期化する',
    night: 'システムに従ってください',
    style_night_tooltip: 'システムに従って自動的にスタイルを切り替える',
    skin_night_tooltip: 'システムに従って自動的にテーマを切り替えます',
    exitclose: 'ログアウトしてページを閉じる',
    enter_or_exit: 'サークルに入る/出る',
    exit: '終了する',
    plugin: 'アプリケーション市場',
    custom: 'カスタマイズ',
    ok: 'わかった',
    filter_nothing: 'データが見つかりません。キーワードを変更してみてください',
    cancel: 'キャンセル',
    remove: '削除する',
    edit: '編集',
    delete: '消去',
    add: '追加',
    learn_more: 'もっと詳しく知る',
    required: '空にすることはできません',
    empty: 'データなし',
    reset_confirm:
      'リセットしてもよろしいですか？ブラックリストとホワイトリスト、後で読むなどのすべてのデータが消去されます',
    notice_placement_demo: 'メッセージの表示例',
    config: '構成、設定',
    local: 'ローカル',
    sync_export: '書き出す',
    select_all: 'すべて選択',
    sync_import: 'ローカル構成のインポート',
    about: '約',
    follow: 'フォローする',
    follow_msg: 'タイムリーな更新のために私たちに従ってください',
    wechat: '公共',
    qq: 'QQグループ',
    support: '激励と支援',
    support_msg: 'あなたの励ましとサポートは私にとって最大のモチベーションです',
    donate_coffee: 'コーヒーを買って',
    share_to_other: '友達と分け合う',
    vote: '五つ星の賞賛',
    vote_msg: '役に立ったら、5つ星のレビューをお願いします🤪',
    to_vote: '五つ星の賞賛',
    to_feedback: 'フィードバックと提案',
    link: 'よく使うリンク',
    usage: 'ご利用案内',
    agreement: 'ユーザー規約',
    privacy: 'プライバシーポリシー',
    faq: 'よくある問題',
    update: '新しいバージョンの更新',
    download_latest: '新しいバージョンをダウンロード',
    version: '現行版',
    search_in_setting: '設定で検索',
    toolbar: 'ツールバー',
    toolbar_msg: 'アイコンをクリックして色をカスタマイズします',
    itemspace: 'ツールバー項目の間隔',
    groupspace: 'ツールバー グループの間隔',
  },
  ko: {
    autorun: '자동 시작',
    autorun_tooltip: '알고리즘을 개선해야 합니다. 조심해서 열어주세요.',
    backtop: '맨 위로',
    backbottom: '맨 아래로 이동',
    feedback: '피드백',
    focus: '원본 강조 표시',
    focus_desc: '읽기 모드로 전환하지 않고 원본 텍스트에서 텍스트 강조 표시',
    focus_opacity: '원본 텍스트의 비텍스트 투명도',
    fullscreen: '전체 화면으로 보기',
    fullscreen_exit: '전체 화면 종료',
    autofullscreen: '자동 전체 화면',
    autofullscreen_tooltip: 'Circle 전체 화면 표시 시작',
    keys: '단축키',
    keys_desc: '바로 가기 키를 사용하여 운영 효율성 향상',
    keys_msg: '입력란 선택 후 키를 눌러 싱글키, 조합키 지원, 싱글키 더블클릭',
    only_in_reader: '읽기 모드에서만 실행 지원',
    lists: '흑백 목록',
    whitelist: '화이트리스트',
    blacklist: '블랙리스트',
    add_whitelist: '현재 페이지를 화이트리스트에 추가',
    remove_whitelist: '화이트리스트에서 현재 페이지 제거',
    toggle_whitelist: '현재 페이지를 화이트리스트에 추가 또는 제거',
    add_whitelist_site: '현재 웹사이트 허용',
    remove_whitelist_site: '화이트리스트에서 현재 사이트 제거',
    toggle_whitelist_site: '화이트리스트에서 현재 사이트 추가 또는 제거',
    add_blacklist: '현재 페이지를 블랙리스트에 추가',
    remove_blacklist: '블랙리스트에서 현재 페이지 제거',
    toggle_blacklist: '현재 페이지를 블랙리스트에 추가 또는 제거',
    add_blacklist_site: '현재 사이트를 블랙리스트에 추가',
    remove_blacklist_site: '블랙리스트에서 현재 사이트 제거',
    toggle_blacklist_site: '블랙리스트에서 현재 웹사이트 추가 또는 제거',
    lists_remove_success: '성공적으로 제거됨',
    lists_add_success: '성공적으로 추가됨',
    title: '제목',
    url: 'URL',
    operate: '작동하다',
    manual: '수동 선택',
    manual_desc:
      '텍스트 인식이 잘못된 경우 텍스트 인식을 지원합니다. "규칙"으로 선택을 기억할 수 있습니다.',
    manual_alert:
      '페이지 하단의 팝업 창을 클릭하여 잘못된 요소(점선 테두리)를 식별하고 마우스를 밀어 올바른 내용을 선택한 다음 확인을 클릭합니다.',
    cover_picture: '표지 사진',
    time: '시각',
    body: '콘텐츠',
    select_done: '완전한 선택',
    menu: '마우스 오른쪽 버튼 클릭 메뉴',
    notice: '메세지 박스',
    outline: '기사 디렉토리',
    outline_desc:
      '콘텐츠 카테고리를 자동으로 식별하여 관심 지점으로 빠르게 이동',
    pin_outline: '고정된 디렉토리',
    hidden_outline: '숨겨진 디렉토리',
    paper: '문구 효과',
    paper_desc: '편지 같은 독서 경험',
    paper_tooltip: '편지지 배경 테두리 과 유사함',
    parser: '파싱 ​​엔진',
    parser_error:
      '콘텐츠 식별에 실패했습니다. 콘텐츠 식별에 도움이 되도록 "수동 선택" 플러그인을 사용하세요.',
    print: '인쇄',
    print_desc: '브라우저의 인쇄 서비스 호출',
    render: '렌더링 엔진',
    style: '스타일',
    page: '페이지',
    font: '기본 글꼴',
    cn_font: '중국어 글꼴',
    font_tooltip: '시스템에 글꼴을 설치해야 합니다.',
    default: '시스템 기본값',
    size: '글꼴 크기',
    width: '페이지 너비',
    space: '글꼴 간격',
    lineheight: '글꼴 줄 높이',
    weight: '글꼴 두께',
    blockspace: '단락 간격',
    indent: '첫 줄 들여쓰기',
    titlealign: '제목 정렬',
    align: '콘텐츠 정렬',
    imagealign: '이미지 정렬',
    imagehide: '이미지 숨기기',
    skin: '주제',
    website: '공식 홈페이지',
    donate: '후원 기부',
    download: '다운로드',
    title1: '1급 타이틀',
    title2: '보조 타이틀',
    title3: '3차 표제',
    title4: '레벨 4 제목',
    title5: '레벨 5 제목',
    title6: '레벨 6 제목',
    layout: '형세',
    margin: '페이지 여백',
    padding_tooltip: '종이 효과가 활성화된 후에만 적용됩니다.',
    copyright: '브라우저 확장 서클 읽기 도우미 레이아웃, 저작권은 $URL$ 소유',
    exception: '이상',
    vote_alert:
      '해당 플랫폼이 없으면 수동으로 확장 마켓에 진입할 수 있으며, 서클을 검색한 후 좋은 댓글을 달 수 있습니다~',
    sure_to_close: '종료 후 더 이상 표시하지 않으시겠습니까?',
    enable: '~할 수 있게 하다',
    disable: '장애가 있는',
    setting: '기본 설정',
    align_left: '왼쪽 정렬',
    align_center: '중앙 정렬',
    align_right: '오른쪽 정렬',
    align_justify: '정당화',
    reset: '초기화',
    reset_tooltip: '기본값으로 되돌리기',
    reset_all: '모든 구성 초기화',
    night: '시스템을 따르다',
    style_night_tooltip: '시스템을 따라 스타일을 자동으로 전환',
    skin_night_tooltip: '시스템을 따라 테마를 자동으로 전환',
    exitclose: '로그아웃하고 페이지 닫기',
    enter_or_exit: '서클 입장/나가기',
    exit: '그만두다',
    plugin: '응용 시장',
    custom: '사용자 정의',
    ok: '확인',
    filter_nothing: '데이터를 찾을 수 없습니다. 키워드를 변경해 보세요.',
    cancel: '취소',
    remove: '제거하다',
    edit: '편집하다',
    delete: '삭제',
    add: '에 추가',
    learn_more: '더 알아보기',
    required: '비워둘 수 없습니다.',
    empty: '데이터 없음',
    reset_confirm:
      '재설정하시겠습니까? 흑백 목록, 나중에 읽기 등의 모든 데이터가 지워집니다.',
    notice_placement_demo: '메시지가 표시되는 위치의 예',
    config: '구성',
    local: '현지의',
    sync_export: '내보내다',
    select_all: '모두 선택',
    sync_import: '로컬 구성 가져오기',
    about: '~에 대한',
    follow: '팔로우',
    follow_msg: '적시 업데이트를 위해 우리를 따르십시오',
    wechat: '공개',
    qq: 'QQ 그룹',
    support: '격려와 지원',
    support_msg: '여러분의 격려와 응원이 저에게 가장 큰 힘이 됩니다',
    donate_coffee: '커피 사줘',
    share_to_other: '친구와 공유',
    vote: '별 다섯 개 칭찬',
    vote_msg: '도움이 되셨다면 별 5개 리뷰를 남겨주세요 🤪',
    to_vote: '별 다섯 개 칭찬',
    to_feedback: '피드백 및 제안',
    link: '가장 많이 사용하는 링크',
    usage: '사용자의 안내',
    agreement: '사용자 계약',
    privacy: '개인 정보 정책',
    faq: '일반적인 문제',
    update: '새 버전 업데이트',
    download_latest: '새 버전 다운로드',
    version: '현재 버전',
    search_in_setting: '환경 설정에서 검색',
    toolbar: '도구 모음',
    toolbar_msg: '색상을 사용자 정의하려면 아이콘을 클릭하십시오.',
    itemspace: '도구 모음 항목 간격',
    groupspace: '도구 모음 그룹 간격',
  },
  th: {
    autorun: 'สตาร์ทอัตโนมัติ',
    autorun_tooltip:
      'อัลกอริทึมต้องได้รับการปรับปรุง โปรดเปิดด้วยความระมัดระวัง',
    backtop: 'กลับไปด้านบน',
    backbottom: 'ไปที่ด้านล่าง',
    feedback: 'ข้อเสนอแนะ',
    focus: 'เน้นต้นฉบับ',
    focus_desc: 'โดยไม่ต้องเข้าสู่โหมดการอ่าน เน้นข้อความในข้อความต้นฉบับ',
    focus_opacity: 'ความโปร่งใสที่ไม่ใช่ข้อความในข้อความต้นฉบับ',
    fullscreen: 'ดูแบบเต็มหน้าจอ',
    fullscreen_exit: 'ออกจากโหมดเต็มหน้าจอ',
    autofullscreen: 'เต็มหน้าจออัตโนมัติ',
    autofullscreen_tooltip: 'เข้าสู่การแสดงเต็มหน้าจอแบบวงกลม',
    keys: 'ปุ่มลัด',
    keys_desc: 'ใช้ปุ่มลัดเพื่อปรับปรุงประสิทธิภาพการดำเนินงาน',
    keys_msg:
      'กดปุ่มหลังจากเลือกช่องป้อนข้อมูล รองรับปุ่มเดียว ปุ่มผสม และดับเบิลคลิกปุ่มเดียว',
    only_in_reader: 'รองรับการทำงานในโหมดการอ่านเท่านั้น',
    lists: 'รายการขาวดำ',
    whitelist: 'บัญชีขาว',
    blacklist: 'บัญชีดำ',
    add_whitelist: 'เพิ่มหน้าปัจจุบันไปยังไวท์ลิสต์',
    remove_whitelist: 'ลบหน้าปัจจุบันออกจากไวท์ลิสต์',
    toggle_whitelist: 'เพิ่มหรือลบหน้าปัจจุบันไปยังรายการที่อนุญาตพิเศษ',
    add_whitelist_site: 'ไวท์ลิสต์เว็บไซต์ปัจจุบัน',
    remove_whitelist_site: 'ลบไซต์ปัจจุบันออกจากรายการที่อนุญาต',
    toggle_whitelist_site: 'เพิ่มหรือลบไซต์ปัจจุบันออกจากรายการที่อนุญาตพิเศษ',
    add_blacklist: 'เพิ่มหน้าปัจจุบันในบัญชีดำ',
    remove_blacklist: 'ลบหน้าปัจจุบันออกจากบัญชีดำ',
    toggle_blacklist: 'เพิ่มหรือลบหน้าปัจจุบันไปยังบัญชีดำ',
    add_blacklist_site: 'เพิ่มไซต์ปัจจุบันในบัญชีดำ',
    remove_blacklist_site: 'ลบไซต์ปัจจุบันออกจากบัญชีดำ',
    toggle_blacklist_site: 'เพิ่มหรือลบเว็บไซต์ปัจจุบันออกจากบัญชีดำ',
    lists_remove_success: 'นำออกเรียบร้อยแล้ว',
    lists_add_success: 'เพิ่มเรียบร้อยแล้ว',
    title: 'ชื่อ',
    url: 'URL',
    operate: 'ดำเนินงาน',
    manual: 'การเลือกด้วยตนเอง',
    manual_desc:
      'เมื่อการจดจำข้อความไม่ถูกต้อง ช่วยในการจดจำข้อความ ด้วย "กฎ" คุณสามารถจำตัวเลือกได้',
    manual_alert:
      'คลิกหน้าต่างป๊อปอัปที่ด้านล่างของหน้าเพื่อระบุองค์ประกอบที่ไม่ถูกต้อง (เส้นขอบจุด) เลื่อนเมาส์เพื่อเลือกเนื้อหาที่ถูกต้องแล้วคลิกตกลง',
    cover_picture: 'ภาพหน้าปก',
    time: 'เวลา',
    body: 'เนื้อหา',
    select_done: 'เลือกได้ครบ',
    menu: 'เมนูคลิกขวา',
    notice: 'กล่องข้อความ',
    outline: 'ไดเรกทอรีบทความ',
    outline_desc:
      'ระบุหมวดหมู่ของเนื้อหาโดยอัตโนมัติเพื่อนำทางไปยังจุดสนใจของคุณอย่างรวดเร็ว',
    pin_outline: 'ไดเร็กทอรีปักหมุด',
    hidden_outline: 'ไดเรกทอรีที่ซ่อนอยู่',
    paper: 'เอฟเฟกต์เครื่องเขียน',
    paper_desc: 'ประสบการณ์การอ่านที่เหมือนตัวอักษร',
    paper_tooltip: 'คล้ายกับเส้นขอบพื้นหลังสเตชันเนอรี',
    parser: 'การแยกวิเคราะห์เครื่องยนต์',
    parser_error:
      'การระบุเนื้อหาล้มเหลว โปรดใช้ปลั๊กอิน "การเลือกด้วยตนเอง" เพื่อช่วยในการระบุเนื้อหา',
    print: 'พิมพ์',
    print_desc: 'เรียกใช้บริการพิมพ์ของเบราว์เซอร์',
    render: 'เครื่องยนต์เรนเดอร์',
    style: 'สไตล์',
    page: 'หน้าหนังสือ',
    font: 'แบบอักษรเริ่มต้น',
    cn_font: 'อักษรจีน',
    font_tooltip: 'ต้องติดตั้งฟอนต์บนระบบ',
    default: 'ค่าเริ่มต้นของระบบ',
    size: 'ขนาดตัวอักษร',
    width: 'ความกว้างของหน้า',
    space: 'การเว้นวรรคแบบอักษร',
    lineheight: 'ความสูงของบรรทัดตัวอักษร',
    weight: 'น้ำหนักตัวอักษร',
    blockspace: 'การเว้นวรรค',
    indent: 'เยื้องบรรทัดแรก',
    titlealign: 'การจัดตำแหน่งชื่อเรื่อง',
    align: 'การจัดตำแหน่งเนื้อหา',
    imagealign: 'การจัดตำแหน่งภาพ',
    imagehide: 'ซ่อนภาพ',
    skin: 'ธีม',
    website: 'หน้าแรกอย่างเป็นทางการ',
    donate: 'บริจาคสนับสนุน',
    download: 'ดาวน์โหลด',
    title1: 'ชื่อระดับแรก',
    title2: 'ชื่อรอง',
    title3: 'หัวเรื่องระดับอุดมศึกษา',
    title4: 'ระดับ 4 หัวเรื่อง',
    title5: 'ระดับ 5 หัวเรื่อง',
    title6: 'ระดับ 6 หัวเรื่อง',
    layout: 'เลย์เอาต์',
    margin: 'ระยะขอบหน้า',
    padding_tooltip: 'มันจะมีผลหลังจากเปิดใช้งานเอฟเฟกต์กระดาษเท่านั้น',
    copyright:
      'รูปแบบตัวช่วยการอ่านแบบวงกลมของส่วนขยายเบราว์เซอร์ ลิขสิทธิ์ของ $URL$',
    exception: 'ผิดปกติ',
    vote_alert:
      'หากไม่พบแพลตฟอร์มที่เกี่ยวข้อง คุณสามารถเข้าสู่ตลาดส่วนขยายได้ด้วยตนเอง และแสดงความคิดเห็นที่ดีหลังจากค้นหา Circle ~',
    sure_to_close: 'ปิดแล้วอย่าโชว์อีกนะ แน่ใจ?',
    enable: 'เปิดใช้งาน',
    disable: 'พิการ',
    setting: 'การตั้งค่า',
    align_left: 'จัดชิดซ้าย',
    align_center: 'จัดกึ่งกลาง',
    align_right: 'จัดชิดขวา',
    align_justify: 'มีเหตุผล',
    reset: 'รีเซ็ต',
    reset_tooltip: 'เปลี่ยนกลับเป็นค่าเริ่มต้น',
    reset_all: 'เริ่มต้นการกำหนดค่าทั้งหมด',
    night: 'ทำตามระบบ',
    style_night_tooltip: 'ทำตามระบบเพื่อเปลี่ยนรูปแบบโดยอัตโนมัติ',
    skin_night_tooltip: 'ทำตามระบบเพื่อสลับธีมโดยอัตโนมัติ',
    exitclose: 'ออกจากระบบและปิดหน้า',
    enter_or_exit: 'เข้า/ออกจากวงกลม',
    exit: 'เลิก',
    plugin: 'ตลาดแอพพลิเคชั่น',
    custom: 'ปรับแต่ง',
    ok: 'ตกลง',
    filter_nothing: 'ไม่พบข้อมูล ลองเปลี่ยนคีย์เวิร์ด',
    cancel: 'ยกเลิก',
    remove: 'ลบ',
    edit: 'แก้ไข',
    delete: 'ลบ',
    add: 'เพิ่ม',
    learn_more: 'เรียนรู้เพิ่มเติม',
    required: 'ไม่สามารถเว้นว่างได้',
    empty: 'ไม่มีข้อมูล',
    reset_confirm:
      'แน่ใจว่าจะรีเซ็ต? ข้อมูลทั้งหมดเช่นรายการขาวดำ อ่านในภายหลัง ฯลฯ จะถูกล้าง',
    notice_placement_demo: 'ตัวอย่างตำแหน่งที่ข้อความปรากฏขึ้น',
    config: 'กำหนดค่า',
    local: 'ท้องถิ่น',
    sync_export: 'ส่งออก',
    select_all: 'เลือกทั้งหมด',
    sync_import: 'นำเข้าการกำหนดค่าภายในเครื่อง',
    about: 'เกี่ยวกับ',
    follow: 'ตามเรามา',
    follow_msg: 'ติดตามเราสำหรับการปรับปรุงทันเวลา',
    wechat: 'ประชาชน',
    qq: 'กลุ่ม QQ',
    support: 'กำลังใจและกำลังใจ',
    support_msg: 'กำลังใจและกำลังใจของคุณคือกำลังใจที่ดีที่สุดสำหรับฉัน',
    donate_coffee: 'ซื้อกาแฟให้ฉัน',
    share_to_other: 'แบ่งปันกับเพื่อน ๆ',
    vote: 'ห้าดาวสรรเสริญ',
    vote_msg: 'ถ้ามันช่วยคุณได้ ให้เรารีวิวห้าดาว 🤪',
    to_vote: 'ห้าดาวสรรเสริญ',
    to_feedback: 'ข้อเสนอแนะและข้อเสนอแนะ',
    link: 'ลิงค์ที่ใช้บ่อยที่สุด',
    usage: 'คำแนะนำผู้ใช้',
    agreement: 'ข้อตกลงการใช้',
    privacy: 'นโยบายความเป็นส่วนตัว',
    faq: 'ปัญหาที่พบบ่อย',
    update: 'อัพเดทเวอร์ชั่นใหม่',
    download_latest: 'ดาวน์โหลดเวอร์ชันใหม่',
    version: 'เวอร์ชั่นปัจจุบัน',
    search_in_setting: 'ค้นหาในการตั้งค่า',
    toolbar: 'แถบเครื่องมือ',
    toolbar_msg: 'คลิกที่ไอคอนเพื่อปรับแต่งสี',
    itemspace: 'ระยะห่างรายการแถบเครื่องมือ',
    groupspace: 'ระยะห่างกลุ่มแถบเครื่องมือ',
  },
  zh_TW: {
    autorun: '自動啟動',
    autorun_tooltip: '算法待完善，謹慎開啟',
    backtop: '返回頂部',
    backbottom: '導航到底部',
    feedback: '問題反饋',
    focus: '高亮原文',
    focus_desc: '不進入閱讀模式的情況下，高亮顯示原文中的正文',
    focus_opacity: '原文中的非正文透明度',
    fullscreen: '全屏查看',
    fullscreen_exit: '退出全屏',
    autofullscreen: '自動全屏',
    autofullscreen_tooltip: '進入 Circle 全屏幕展示',
    keys: '快捷鍵',
    keys_desc: '使用快捷鍵提高操作效率',
    keys_msg: '選中輸入框後按鍵，支持單鍵、組合鍵和雙擊單鍵',
    only_in_reader: '僅支持在閱讀模式下運行',
    lists: '黑白名單',
    whitelist: '白名單',
    blacklist: '黑名單',
    add_whitelist: '將當前頁加入白名單',
    remove_whitelist: '從白名單將當前頁移除',
    toggle_whitelist: '將當前頁加入或移除白名單',
    add_whitelist_site: '將當前網站加入白名單',
    remove_whitelist_site: '從白名單將當前網站移除',
    toggle_whitelist_site: '將當前網站加入或移除白名單',
    add_blacklist: '將當前頁加入黑名單',
    remove_blacklist: '從黑名單將當前頁移除',
    toggle_blacklist: '將當前頁加入或移除黑名單',
    add_blacklist_site: '將當前網站加入黑名單',
    remove_blacklist_site: '從黑名單將當前網站移除',
    toggle_blacklist_site: '將當前網站加入或移除黑名單',
    lists_remove_success: '移除成功',
    lists_add_success: '添加成功',
    title: '標題',
    url: '網址',
    operate: '操作',
    manual: '手動選擇',
    manual_desc: '正文識別錯誤的時候，輔助識別正文。配合 “規則” 可以記住選擇',
    manual_alert:
      '點擊頁面底部彈窗識別錯誤（虛線邊框）的元素後，滑動鼠標選擇正確的內容點擊確定',
    cover_picture: '封面圖',
    time: '時間',
    body: '內容',
    select_done: '完成選擇',
    menu: '右鍵菜單',
    notice: '消息提示框',
    outline: '文章目錄',
    outline_desc: '自動識別內容中的目錄，快速導航到你感興趣的位置',
    pin_outline: '釘住目錄',
    hidden_outline: '隱藏目錄',
    paper: '信紙效果',
    paper_desc: '信件一樣的閱讀體驗',
    paper_tooltip: '類似信紙背景邊框',
    parser: '解析引擎',
    parser_error: '內容識別失敗，請使用 “手動選擇” 插件輔助來識別內容',
    print: '打印',
    print_desc: '調用瀏覽器的打印服務',
    render: '渲染引擎',
    style: '樣式',
    page: '頁面',
    font: '默認字體',
    cn_font: '中文字體',
    font_tooltip: '需要係統安裝該字體',
    default: '系統默認',
    size: '字體大小',
    width: '頁面寬度',
    space: '字體間距',
    lineheight: '字體行高',
    weight: '字體粗細',
    blockspace: '段落間距',
    indent: '首行縮進',
    titlealign: '標題對齊',
    align: '內容對齊',
    imagealign: '圖片對齊',
    imagehide: '隱藏圖片',
    skin: '主題',
    website: '官方主頁',
    donate: '捐贈支持',
    download: '下載',
    title1: '一級標題',
    title2: '二級標題',
    title3: '三級標題',
    title4: '四級標題',
    title5: '五級標題',
    title6: '六級標題',
    layout: '佈局',
    margin: '頁外邊距',
    padding_tooltip: '紙張效果啟用之後才生效',
    copyright: '瀏覽器擴展 Circle 閱讀助手排版，版權歸 $URL$ 所有',
    exception: '異常',
    vote_alert:
      '未找到對應的平台，你可以手動進入擴展市場，搜素到 Circle 後給予好評 ～',
    sure_to_close: '關閉後不再顯示，確定嗎？',
    enable: '啟用',
    disable: '禁用',
    setting: '偏好設置',
    align_left: '左對齊',
    align_center: '居中對齊',
    align_right: '右對齊',
    align_justify: '兩端對齊',
    reset: '重置',
    reset_tooltip: '恢復為默認',
    reset_all: '初始化所有配置',
    night: '跟隨系統',
    style_night_tooltip: '跟隨系統自動切換樣式',
    skin_night_tooltip: '跟隨系統自動切換主題',
    exitclose: '退出並關閉網頁',
    enter_or_exit: '進入/退出 Circle',
    exit: '退出',
    plugin: '應用市場',
    custom: '自定義',
    ok: '好的',
    filter_nothing: '沒有找到任何數據，更換關鍵字試試',
    cancel: '取消',
    remove: '移除',
    edit: '編輯',
    delete: '刪除',
    add: '添加',
    learn_more: '了解詳情',
    required: '不能為空',
    empty: '暫無數據',
    reset_confirm: '確認重置嗎？黑白名單、稍後讀等所有的數據都將被清空',
    notice_placement_demo: '消息出現的位置示例',
    config: '配置',
    local: '本地',
    sync_export: '導出',
    select_all: '全選',
    sync_import: '導入本地配置',
    about: '關於',
    follow: '關注我們',
    follow_msg: '關注我們及時獲取更新動態',
    wechat: '公眾號',
    qq: 'QQ 群',
    support: '鼓勵與支持',
    support_msg: '您的鼓勵與支持是對我最大的動力',
    donate_coffee: '請我喝咖啡',
    share_to_other: '分享給小伙伴',
    vote: '五星好評',
    vote_msg: '如果幫助到了你，給我們一個五星好評吧 🤪',
    to_vote: '五星好評',
    to_feedback: '反饋與建議',
    link: '常用鏈接',
    usage: '使用指南',
    agreement: '用戶協議',
    privacy: '隱私政策',
    faq: '常見問題',
    update: '版本更新',
    download_latest: '下載新版',
    version: '當前版本',
    search_in_setting: '在偏好設置中搜索',
    toolbar: '工具欄',
    toolbar_msg: '點擊圖標可以自定義顏色',
    itemspace: '工具欄項距',
    groupspace: '工具欄組距',
  },
  'zh-CN': {
    autorun: '自动启动',
    autorun_tooltip: '算法待完善，谨慎开启',
    backtop: '返回顶部',
    backbottom: '导航到底部',
    feedback: '问题反馈',
    focus: '高亮原文',
    focus_desc: '不进入阅读模式的情况下，高亮显示原文中的正文',
    focus_opacity: '原文中的非正文透明度',
    fullscreen: '全屏查看',
    fullscreen_exit: '退出全屏',
    autofullscreen: '自动全屏',
    autofullscreen_tooltip: '进入 Circle 全屏幕展示',
    keys: '快捷键',
    keys_desc: '使用快捷键提高操作效率',
    keys_msg: '选中输入框后按键，支持单键、组合键和双击单键',
    only_in_reader: '仅支持在阅读模式下运行',
    lists: '黑白名单',
    whitelist: '白名单',
    blacklist: '黑名单',
    add_whitelist: '将当前页加入白名单',
    remove_whitelist: '从白名单将当前页移除',
    toggle_whitelist: '将当前页加入或移除白名单',
    add_whitelist_site: '将当前网站加入白名单',
    remove_whitelist_site: '从白名单将当前网站移除',
    toggle_whitelist_site: '将当前网站加入或移除白名单',
    add_blacklist: '将当前页加入黑名单',
    remove_blacklist: '从黑名单将当前页移除',
    toggle_blacklist: '将当前页加入或移除黑名单',
    add_blacklist_site: '将当前网站加入黑名单',
    remove_blacklist_site: '从黑名单将当前网站移除',
    toggle_blacklist_site: '将当前网站加入或移除黑名单',
    lists_remove_success: '移除成功',
    lists_add_success: '添加成功',
    title: '标题',
    url: '网址',
    operate: '操作',
    manual: '手动选择',
    manual_desc: '正文识别错误的时候，辅助识别正文。配合 “规则” 可以记住选择',
    manual_alert:
      '点击页面底部弹窗识别错误（虚线边框）的元素后，滑动鼠标选择正确的内容点击确定',
    cover_picture: '封面图',
    time: '时间',
    body: '内容',
    select_done: '完成选择',
    menu: '右键菜单',
    notice: '消息提示框',
    outline: '文章目录',
    outline_desc: '自动识别内容中的目录，快速导航到你感兴趣的位置',
    pin_outline: '钉住目录',
    hidden_outline: '隐藏目录',
    paper: '信纸效果',
    paper_desc: '信件一样的阅读体验',
    paper_tooltip: '类似信纸背景边框',
    parser: '解析引擎',
    parser_error: '内容识别失败，请使用 “手动选择” 插件辅助来识别内容',
    print: '打印',
    print_desc: '调用浏览器的打印服务',
    render: '渲染引擎',
    style: '样式',
    page: '页面',
    font: '默认字体',
    cn_font: '中文字体',
    font_tooltip: '需要系统安装该字体',
    default: '系统默认',
    size: '字体大小',
    width: '页面宽度',
    space: '字体间距',
    lineheight: '字体行高',
    weight: '字体粗细',
    blockspace: '段落间距',
    indent: '首行缩进',
    titlealign: '标题对齐',
    align: '内容对齐',
    imagealign: '图片对齐',
    imagehide: '隐藏图片',
    skin: '主题',
    website: '官方主页',
    donate: '捐赠支持',
    download: '下载',
    title1: '一级标题',
    title2: '二级标题',
    title3: '三级标题',
    title4: '四级标题',
    title5: '五级标题',
    title6: '六级标题',
    layout: '布局',
    margin: '页外边距',
    padding_tooltip: '纸张效果启用之后才生效',
    copyright: '浏览器扩展 Circle 阅读助手排版，版权归 $URL$ 所有',
    exception: '异常',
    vote_alert:
      '未找到对应的平台，你可以手动进入扩展市场，搜素到 Circle 后给予好评 ～',
    sure_to_close: '关闭后不再显示，确定吗？',
    enable: '启用',
    disable: '禁用',
    setting: '偏好设置',
    align_left: '左对齐',
    align_center: '居中对齐',
    align_right: '右对齐',
    align_justify: '两端对齐',
    reset: '重置',
    reset_tooltip: '恢复为默认',
    reset_all: '初始化所有配置',
    night: '跟随系统',
    style_night_tooltip: '跟随系统自动切换样式',
    skin_night_tooltip: '跟随系统自动切换主题',
    exitclose: '退出并关闭网页',
    enter_or_exit: '进入/退出 Circle',
    exit: '退出',
    plugin: '应用市场',
    custom: '自定义',
    ok: '好的',
    filter_nothing: '没有找到任何数据，更换关键字试试',
    cancel: '取消',
    remove: '移除',
    edit: '编辑',
    delete: '删除',
    add: '添加',
    learn_more: '了解详情',
    required: '不能为空',
    empty: '暂无数据',
    reset_confirm: '确认重置吗？黑白名单、稍后读等所有的数据都将被清空',
    notice_placement_demo: '消息出现的位置示例',
    config: '配置',
    local: '本地',
    sync_export: '导出',
    select_all: '全选',
    sync_import: '导入本地配置',
    about: '关于',
    follow: '关注我们',
    follow_msg: '关注我们及时获取更新动态',
    wechat: '公众号',
    qq: 'QQ 群',
    support: '鼓励与支持',
    support_msg: '您的鼓励与支持是对我最大的动力',
    donate_coffee: '请我喝咖啡',
    share_to_other: '分享给小伙伴',
    vote: '五星好评',
    vote_msg: '如果帮助到了你，给我们一个五星好评吧 🤪',
    to_vote: '五星好评',
    to_feedback: '反馈与建议',
    link: '常用链接',
    usage: '使用指南',
    agreement: '用户协议',
    privacy: '隐私政策',
    faq: '常见问题',
    update: '版本更新',
    download_latest: '下载新版',
    version: '当前版本',
    search_in_setting: '在偏好设置中搜索',
    toolbar: '工具栏',
    toolbar_msg: '点击图标可以自定义颜色',
    itemspace: '工具栏项距',
    groupspace: '工具栏组距',
  },
};
